
<!-- MES STYLES -->
<?php echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleListeDossiersPatients.css');?>

<!-- MES JS -->
<?php echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsListeAutoSignalement.js');?>


<?php 
use Consultation\View\Helper\DateHelper;
$Control = new DateHelper();?>
<style>
#contenuInterface{ visibility: hidden; }
</style>

<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenuInterface').fadeIn().css({'visibility':'visible'});
	 
});
</script>


<div id="titre" style='font-family: police2; text-decoration:none; color: green; font-size: 18px; font-weight: bold; padding-left: 20px;'><iS style='font-size: 25px;'>&curren;</iS> <span> LISTE DES AUTO-SIGNALEMENTS </span></div>
<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>
<div id="contenuInterface" >
<div id="contenu" >

		<table class="table table-bordered tab_list_mini" id="patientAdmis">
			<thead>
				<tr style="height:45px; width:100%;">
					<th id="prenom" >PRENOM</th>
					<th id="nom" >NOM</th>
					<th id="date" >D. NAISSANCE</th>
					<th style="width: 12px;">AGE</th>
					<th id="sexe" >SEXE</th>
					<th style="width: 7%;">ADRESSE</th>
					<th id="numero_dossier" >TELEPHONE</th>
					<th id="effectuer" >OPTIONS</th>
				</tr>
			</thead>

			<tbody id="donnees" class="liste_patient" style="font-family: times new roman; font-size: 19px; ">

            <!-- ******* On affiche la liste des patients ****** -->
            
			</tbody>

			<tfoot id="foot" class="foot_style">
				<tr>
					<th id="prenom_" style="width: 18%;"><input type="text" name="search_browser" value=" Pr&eacute;nom" class="search_init" /></th>
					<th id="nom_" style="width: 14%;"><input type="text" name="search_browser" value=" Nom" class="search_init" /></th>
					<th id="date_" style="width: 12%;"><input type="text" name="search_browser" value=" Date naissance" class="search_init" /></th>
					<th id="adresse_" style="width: 12px;"><input type="text" name="search_browser" value=" Age" class="search_init" /></th>
					<th id="sexe_" style="width: 7%;"><input type="text" name="search_browser" value=" Sexe" class="search_init" /></th>
					<th id="age_" style="width: 7%;"><input type="text" name="search_browser" value=" Adresse" class="search_init" /></th>
					<th id="numero_dossier_" style="width: 14%;"><input type="text" name="search_browser" value=" Telephone" class="search_init" /></th>
					<th id="effectuer_" style="width: 10%;"><input type="hidden" name="search_browser" value="" class="" /></th>
				</tr>
			</tfoot>
		</table>

</div>

<div id="vue_patient" style="display: none;">

</div>

</div>

<script>
	initialisation();
</script>