<script>
var base_url = window.location.toString();
var tabUrl = base_url.split("public");
//POUR LE MENU GAUCHE dans -elementgauche.phtml
$('#plus_menu_consultations').toggle(true);
$("#menu_consultations").replaceWith("<li id='menu_consultations' style='background:#4a5765;'><a href=''><span style='margin-left:0px; color: #ffffff; font-weight:bold; font-size:20px; font-family:Times New Roman;'> <img style='display: inline;' src='"+tabUrl[0]+"public/images_icons/moin-green2.png' alt='Liste' /> Consultations </span></a></li>");
dep_menu_consultation1();
$('#menu_consultations_style').css({'font-weight':'bold','color':'white','font-size':'22px'});
</script>

<?php use Consultation\View\Helper\DateHelper; ?>
<?php $Control = new DateHelper(); ?>

<!-- LES SCRIPS DES PLUGINS ET DES JS -->
<?php 
  echo $this->headLink()->appendStylesheet($this->basePath().'/css/pikachoose/bottom.css');
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.jcarousel.min.js');
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/pikachoose/jquery.pikachoose.min.js');
  
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.js');
  echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/fancybox/source/jquery.fancybox.css');
  
  echo $this->headLink()->appendStylesheet($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.css');
  echo $this->headScript()->appendFile($this->basePath().'/js/plugins/dateTimePicker/jquery-ui-timepicker-addon.js');
    
  echo $this->headScript()->appendFile($this->basePath().'/js/consultation/jsConsulter.js');
?>

<!-- LES SCRIPS CSS -->
<?php 
  echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleConsulter.css');
  echo $this->headLink()->appendStylesheet($this->basePath().'/css/consultation/styleMonstyle.css');
?>
      


















<script>
$(window).load(function () {

	$('#wait').toggle(false);
	$('#contenu').fadeIn().css({'visibility':'visible'});
	 
});
</script>

<div id="wait" style="color: gray; font-size: 20px; text-align: center; margin-top: 80px;" > <span> Chargement ... </span> </div>

<div id="contenu" >

  <?php 
	$form = $this->form;
	$form->setName('formConsultation');
 
    if($this->typeDeConsultation == 1){
        $form->setAttribute('action', $this->url('consultation', array('action'=>'enregistrer-consultation-suivi')));
    }else{
        $form->setAttribute('action', $this->url('consultation', array('action'=>'enregistrer-consultation')));
    }
  	
	$form->setAttribute('method', 'post');
	$form->prepare();
	echo $this->form()->openTag($form); 
  ?>

<div id="accordions"> 

	 <!--*************** Accordeon ETAT CIVIL ******************-->
	 <!--*************** Accordeon ETAT CIVIL ******************-->
	 <!--*************** Accordeon ETAT CIVIL ******************-->
	 
	 <!--*1*-->
	 
     <div style='width:160px; font-family: police2;font-size: 17px; font-weight: bold;'>Etat Civil</div>
     <div style='max-height: 400px;'>

       <table style="width: 100%;">
         
         <tr style="width: 100%;">
         
           <!-- Première colonne photo -->         
           <td style="height: 100px; width: 16%; vertical-align: top;">
             <img id="faces" src='<?php echo $this->basePath().'/images/photos_patients/identite.jpg';?>'  style='float:left; margin-right:40px; width:105px; height:105px;'/>
             <div style=' left: 40px; top: 160px; font-family: time new romans; position: absolute; '> Age: <span style='font-size:19px; font-family: time new romans; color: green; font-weight: bold;'> <?php echo $this->lesdetails['AGE'].' ans'; ?>  </span></div>
           </td> 
           
           
           <!-- Deuxième colonne infos état-civil -->
           <td style="width: 72%;">
           
              <table id="etat_civil" style="width: 100%;">
              
               <tr>
    			   	<td style='width: 27%; font-family: police1;font-size: 12px; vertical-align: top;'>
    			   	
    			   		<div ><a style="text-decoration: underline;">Sexe</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['SEXE'];?></p></div>
    			   		
    			   	</td>
    
    			    <td style='width:35%; font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">Adresse</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['ADRESSE'];?></p></div>
    
    			   	</td>
    			   	
    			   	<td style='width:38%; font-family: police1;font-size: 12px; vertical-align: top;'>
    			   	    <div ><a style="text-decoration: underline;">Profession</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['PROFESSION']?$this->listeProfessions[$this->lesdetails['PROFESSION']]:'';?></p></div>
    			   	</td>
			   </tr>
			  
               <tr style="width: 100%;">
    			   	
    			   	<td style='width:27%; font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">Pr&eacute;nom</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['PRENOM'];?></p></div>
    			   	</td>
    
    			   	<td style='width:35%; font-family: police1;font-size: 12px;'>
    		   		<div ><a style="text-decoration: underline;">T&eacute;l&eacute;phone 1</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->personne->telephone; ?></p></div>
    			   	</td>
    
    			    <td style='width:38%; font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">Nationalit&eacute;</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->patient->nationalite;?></p></div>
    			   	</td>

			   </tr>

			   <tr>
    			    <td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">Nom</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['NOM'];?></p></div>
    			   	</td>
    
				    <td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">T&eacute;l&eacute;phone 2</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->personne->telephone_2; ?></p></div>
    			   	</td>
    			   	
    			   	<td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">Statut matrimonial</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['STATUT_MATRIMONIAL']?$this->listeStatutMatrimonial[$this->lesdetails['STATUT_MATRIMONIAL']]:'';?></p></div>
    			   	</td>
    
			   </tr>

			   <tr>
			    	<td style=' font-family: police1;font-size: 12px;'>
			   		
    			   		<div ><a style="text-decoration: underline; ">Date de naissance</a><br>
    			   		  <p style='font-weight: bold;font-size: 19px;'>
    			   		    <?php 
    			   		    $date_naissance = $this->lesdetails['DATE_NAISSANCE'];
    			   		    if($date_naissance){ echo $Control->convertDate($this->lesdetails['DATE_NAISSANCE']); }else{ echo "";}
    			   		    ?> 
    			   		  </p>
    			   		</div>
			   	
			   		</td>

    			    <td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">R&eacute;gion</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->patient->region; ?></p></div>
    			   	</td>
    
    			   	<td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">R&eacute;gime matrimonial</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->lesdetails['REGIME_MATRIMONIAL']?$this->listeRegimeMatrimonial[$this->lesdetails['REGIME_MATRIMONIAL']]:'';?></p></div>
    			   	</td>

			   </tr>
			   
			   <tr>
    			    <td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">Lieu de naissance</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->personne->lieu_naissance;?></p></div>
    			   	</td>
    
    			   	<td style=' font-family: police1;font-size: 12px;'>
    			   		<div ><a style="text-decoration: underline;">D&eacute;partement</a><br><p style='font-weight: bold;font-size: 19px;'><?php echo $this->patient->departement; ?></p></div>
    			   	</td>
    
    			   	<td style=' font-family: police1;font-size: 12px;'>
    			   	
    			   	</td>

			   </tr>

			  
             </table>
           
           
           </td> 
           
           
           
           <!-- Troisième colonne photo -->
           <td style="width: 12%; vertical-align: top;">
           
             <p style='color: white; opacity: 0.09;'>
               <img id="faces" src='<?php echo $this->basePath().'/images/photos_patients/identite.jpg'?>'  alt="Jonathan Verrecchia" style='float:right; margin-right:15px; width:95px; height:95px;'/>
             </p>
             <span style="position: absolute; right: 63px; top: 150px; color: green; font-family: time new roman; font-size: 17px; "> <?php echo $this->patient->numero_dossier; ?> </span>
             
           </td>
           
         </tr>
         
         
         <!-- Deuxième ligne pour le bas de page -->
         <tr style="width: 100%;">
           <td style="height: 10px; width: 16%;"></td> 
           <td colspan="2"> <div id="barre"></div> </td> 
           
         </tr>
         
         <!-- Troisième ligne pour le bas de page -->
         <tr style="height: 100px; width: 100%;">
           <td style="height: 10px; width: 16%;"></td> 
           
           <td style="width: 72%; vertical-align: top;">
             <table id="numero" style=" padding-top:5px; width: 550px;">
	           <tr style="width: 100%;">
	             <td style="padding-top:5px; width: 70px; font-size: 12px;"> Consultation: </td>
	             <td style="font-weight: bold;"> <?php echo $this->idcons;?></td>
	             <td style="font-weight: bold; width:10px;">|</td>
	             <td style="padding-top:5px; width: 80px; font-size: 12px; "> Date & Heure: </td>
	             <td style="font-weight: bold;"> <?php echo $Control->convertDate($this->date); ?>  -  <?php echo $this->heure;?></td>
	           </tr>
         	 </table>
           </td> 
           
           <td style="width: 12%; vertical-align: top;">
             <div style='color: white; opacity: 1; width:95px; height:40px; float:right'>
               <img  src='<?php echo $this->basePath().'/images_icons/fleur1.jpg'?>'  alt="fleur1" />
             </div>
           </td>
           
         </tr>
       
       
       </table>
  
     </div>
  
  
     <!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
     <!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
     <!-- ************** Accordeon NOUVELLES CONSTANTES ******************-->
     
     <!--*2*-->
     <!--*2*-->
     <!--*2*-->
     <!--*2*-->
     <!--*2*-->
  	 <div style='font-family: police2;font-size: 17px; font-weight: bold;'> Sympt&ocirc;mes </div>
     <div id="plaintesConsSuivi" class="zoneContenuObmre">
       
         <div style="width: 100%; padding: 3px; margin-top: 6px; padding-bottom: 1px; ">
           <table class="plainteEntre plainteEntree_0"></table>
         </div>
         
         <table style="width:100%;" >
           <tr style="width: 100%">
              <td style="width: 20%;">
    	         <div id='plainte_moins' class='examen_physique_pm' onclick='enleverUnePlainte();' style='display: none;'> &minus; </div> 
    	         <div id='plainte_plus'  class='examen_physique_pm' onclick='ajouterUneNouvellePlainte();' style='display: none;'> + </div>
    	      </td>
    	      <td style="width: 80%;" ></td>
    	   </tr>
    	 </table>
    	 <input type="hidden" id="nbPlaintesEntree" name="nbPlaintesEntree">
         <script type="text/javascript">ajouterUneNouvellePlainte();</script>
       
     </div>
     
     
     
     <!-- ********************Antécédents ou Terrain particulier ******************-->
     <!-- ********************Antécédents ou Terrain particulier ******************-->
     <!-- ********************Antécédents ou Terrain particulier ******************--> 
     
     <!--*3*-->
     <!--*3*-->
     <!--*3*-->
     <!--*3*-->
     
     <div style='font-family: police2;font-size: 17px; font-weight: bold;'>Ant&eacute;c&eacute;dents et Historiques</div>  
     <div style='max-height: 500px;'>
  
         <div id="tabsAntecedents">
             <ul>
                <li><a href="#tabss-1">Ant&eacute;c&eacute;dents</a></li>
                <li><a href="#tabss-2">Historiques</a></li>
             </ul>
                                   
	         <div id="tabss-1"> 
	           
		           <!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
		           <!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
		           <!--****** ================== ANTECEDENTS TERRAIN PARTICULIER ================== ****** -->
		           <table id="MenuTerrainParticulier" style="width:100%;">
		                 <tr style="width:100%;">
		                 	<td style="width:33%;">
		                        <div>    
		                            <img class="image1_TP" style='cursor: pointer; position:relative; left: 15%; width: 70%; height: 80%;' src='<?php echo $this->basepath().'/images_icons/image1_AP.png'?>' />
		                        </div>
		                     </td>
		                     <td style="width:34%;">
		                        <div>    
		                            <img class="image1_TP" style='cursor: pointer; position:relative; left: 15%; width: 70%; height: 80%;' src='<?php echo $this->basepath().'/images_icons/image2_AP.png'?>' />
		                        </div>
		                     </td>
		                     <td style="width:33%;">
		                        <div>    
		                            <img class="image2_TP" style='cursor: pointer; position:relative; left: 15%; width: 70%; height: 80%;' src='<?php echo $this->basepath().'/images_icons/image3_AP.png'?>' />
		                        </div>
		                     </td>
		                 </tr>
		           </table>
     
     
             		<table id="HabitudesDeVie" style="width:100%; display: none;">
                        <tr style="width:100%;">
                          <td colspan="4" style="">
                            <div style="width: 100%; font-family: Times New Roman;  color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;" ><iS style='font-size: 25px;'>&curren;</iS> LES HABITUDES DE VIE DU PATIENTS</div>
                          </td>
                        </tr>
                        
                        <tr style="width:100%;">
                          
                          <!--td id="BUcheckbox" style="width: 25%">
                            <div style="float:left;"><label style="width: 100%; height:30px; text-align:right;">Tabagisme </label></div> 
                          </td>
                          
                          <td id="BUcheckbox" style="width: 25%">
                            <div style="float:left;"><label style="width: 100%; height:30px; text-align:right;">Alcoolique </label></div> 
                          </td>
                          
                          <td id="BUcheckbox" style="width: 25%">
                            <div style="float:left;"><label style="width: 100%; height:30px; text-align:right;">Cosommateur de drogue </label></div> 
                          </td>
                          
                          <td id="BUcheckbox" style="width: 25%">
                            <div style="float:left;"><label style="width: 100%; height:30px; text-align:right;">Autres &agrave; pr&eacute;ciser </label></div> 
                          </td-->
                          
                          
						  <td style="width: 100%">
                             <div style="width: 100%; background: re; padding: 3px; padding-bottom: 1px;">
                                   
                                   <table style="width: 100%;" >
                                 	 <tr style="width: 100%" class="designStyleLabel">
                                 		        
                                 	   <td style="padding-right: 23px; width: 25%">
                                 	     <label class="container" style="width: 100%; height:30px; text-align:left;">
            		                       <span style='font-size: 11px;'>&#10148; </span>
            		                       
            		                       <span>Tabagisme</span> 
  										   <input type="checkbox" >           		                         
  										   <span class="checkmark"></span>
  											 
            		                     </label>
                                 	   </td>
                                 	   
                                 	   <td style="padding-right: 23px; width: 25%">
                                 	     <label class="container" style="width: 100%; height:30px; text-align:left;">
            		                         <span style='font-size: 11px;'>&#10148; </span>
 
											 <span>Alcoolisme</span> 
  											 <input type="checkbox" >           		                         
  											 <span class="checkmark"></span>
										   
            		                     </label>
                                 	   </td>
                                 	   
                                 	   <td style="padding-right: 23px; width: 25%">
                                 	     <label class="container" style="width: 100%; height:30px; text-align:left;">
            		                       <span style='font-size: 11px;'>&#10148; </span>
            		                       
            		                       <span>Cosommateur de drogue</span> 
  										   <input type="checkbox" >           		                         
  										   <span class="checkmark"></span>
  											 
            		                     </label>
                                 	   </td>
                                 	   
                                 	   <td style="padding-right: 23px; width: 25%">
                                 	     <label class="container" style="width: 100%; height:30px; text-align:left;">
            		                       <span style='font-size: 11px;'>&#10148; </span>
            		                       
            		                       <span>Autres &agrave; pr&eacute;ciser</span>
  										   <input type="checkbox" >           		                         
  										   <span class="checkmark"></span>
            		                        
            		                     </label>
                                 	   </td>
                                 		        
                           		     </tr>
            	 			       </table>
            	 			       
                             </div>
                 		  </td>
                
                 
                          
                        </tr>
                        
                        
                        
                        <tr style="width:100%;">
                            <td colspan="4" class="TerminerContenuDiabetiqueConnu styleBouton" style='width:100%; padding-bottom: 5px; padding-top: 25px;' colspan="4"> </td>
                         </tr>
                         
                         
                   </table>
                   
                   <table id="AntecedentMedicaux" style="width:100%;  display: none;">
                        <tr style="width:100%;">
                          <td colspan="3" style="width:60%;" >
                            <div style="font-family: Times New Roman;  color: green; font-size: 17px; font-weight: bold; padding-bottom: 10px;" ><iS style='font-size: 25px;'>&curren;</iS> LES ANT&Eacute;C&Eacute;DENTS M&Eacute;DICAUX</div>
                          </td>
                          <td>  </td>
                          <td>  </td>
                        </tr>
                        
                        <tr style="width:100%; height: 50px; ">
                          <td id="BUcheckbox" style="width: 20%; ">
                            <div >
                              <label  style="width: 90%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                 <span> 
                                    <img class="imageValiderDiabeteAM" style='cursor: pointer; padding-right: 10px;' src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />  
                                 </span> 
                                 
                                 Diab&egrave;te 
                                 <?php /* echo $this->formRow($form->get('DiabeteAM'));*/ ?>
                              </label>
                            </div> 
                          </td>
                        
                          <td id="BUcheckbox" style="width: 20%; ">
                            <div >
                             <label style="width: 90%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                <span> 
                                   <img class="imageValiderHtaAM" style='cursor: pointer; padding-right: 10px;' src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />  
                                </span> 
                                 
                                HTA 
                                <?php /*echo $this->formRow($form->get('htaAM'));*/ ?>
                             </label>
                            </div> 
                          </td>
                        
                          <td id="BUcheckbox" style="width: 20%; ">
                            <div >
                             <label style="width: 90%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                <span> 
                                   <img class="imageValiderDrepanocytoseAM" style='cursor: pointer; padding-right: 0px;' src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />  
                                </span> 
                                
                                Dr&eacute;panocytose <?php /* echo $this->formRow($form->get('drepanocytoseAM'));*/ ?>
                             </label>
                            </div> 
                          </td>
                          
                          <td id="BUcheckbox" style="width: 20%; ">
                            <div >
                             <label style="width: 90%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                <span> 
                                   <img class="imageValiderDislipidemieAM" style='cursor: pointer; padding-right: 10px;' src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />  
                                </span>  
                                
                                Dislipid&eacute;mie  <?php /*echo $this->formRow($form->get('dislipidemieAM'));*/ ?>
                             </label>
                            </div> 
                          </td>
                          
                          <td id="BUcheckbox" style="width: 20%; ">
                            <div >
                             <label style="width: 90%; height:30px; text-align:right; font-family: time new romans; font-size: 18px;">
                                <span> 
                                   <img class="imageValiderAsthmeAM" style='cursor: pointer; padding-right: 10px;' src='<?php echo $this->basepath().'/images_icons/tick-icon2.png'?>' />  
                                </span> 
                             
                                Asthme  <?php /*echo $this->formRow($form->get('asthmeAM'));*/?>
                             </label>
                            </div> 
                          </td>
                          
                        </tr>
                        
                        <tr style="width:100%;">
                           <td colspan="5" class='block' id='thoughtbot' style='display: inline-block;  vertical-align: bottom; width:20%; padding-bottom: 5px; padding-top: 35px;'><div style="float:left;" id="TerminerAntecedentMedicaux">Terminer</div></td>
                        </tr>
                   </table>
     
     
     
     
     
     
     
     
     
     
     
             </div>
            
         </div>
     
     </div>
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
     
        
        
        
     <!-- ******************** FIN SUIVI -- FIN SUIVI ******************-->
     <!-- ******************** FIN SUIVI -- FIN SUIVI ******************-->
     <!-- ******************** FIN SUIVI -- FIN SUIVI ******************-->
     
     
     
     
</div>


<table style="width: 100%; margin-top: 20px;">
    <tr>
     <td style="background-color: #eeeeee; height: 40px;width: 100%; ">
         <p style="text-align: center;"> 
            <button style="font-family: police2;font-size: 18px; font-weight: bold;" id="annulerConsultation"> Annuler </button>
            <button style="font-family: police2;font-size: 18px; font-weight: bold;"> Terminer </button> 
         </p>
     </td>
    </tr>
</table>

<?php echo $this->form()->closeTag();?>


</div>


<!-- POP UP pour Confirmation Annulation -->
<div id="confirmationAnnulation" title="Confirmation de l'annulation" style="display:none;">
    <p style="font-size: 16px;">
      <span style="float:left; margin:0 0px 20px 0; ">
        <img src="<?php echo $this->basePath().'/images_icons/warning_16.png';?>" />
        Etes-vous s&ucirc;r de vouloir annuler les modifications ?
      </span>
    </p>
</div>




<?php if($this->typeDeConsultation == 1){ ?>
  <script>
    $('#depliantSuiviPatient').toggle(true);
  </script>
<?php } ?>